# Supabase credentials
SUPABASE_URL = "https://skxqdntviwyfubafaaxp.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNreHFkbnR2aXd5ZnViYWZhYXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxODczNzIsImV4cCI6MjA3MTc2MzM3Mn0.Jss9z3pAkgrlS86GAcoEKigapn4-2D6C5vsVbcNDmS4"
